name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bio-oil-web-app
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: bio-oil-web-app

      - name: Setup Node and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install JS dependencies
        run: yarn install

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bio-oil-web-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: bio-oil-web-app

      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop
        
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
        continue-on-error: true

      - name: Security audit application code
        run: bundle exec brakeman -q -w2

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
        continue-on-error: true
